# Generated by Django 5.0.6 on 2024-07-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioSesionAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
