# Generated by Django 5.0.6 on 2024-06-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rutCliente',
            field=models.CharField(db_column='rut', max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
